const { withPodfile, createRunOncePlugin } = require('@expo/config-plugins');

/**
 * Xcode 16.3+ ships a Clang that enforces C++20 consteval more strictly than
 * before, which breaks the `fmt` pod (pulled in via RN 0.76's RCT-Folly):
 * build fails with "call to consteval function ... is not a constant
 * expression" in fmt/format-inl.h. fmt itself already has a documented
 * fallback for "broken consteval" Apple Clang versions — it just predates
 * Xcode 16.3, so it isn't in the exclusion list yet. Rather than lean on a
 * preprocessor define and hope it wins the include-order race, patch the
 * `consteval` keyword out of the vendored fmt headers directly on disk, in
 * the Podfile's post_install (after CocoaPods has copied fmt's sources into
 * the sandbox, before Xcode compiles them). ios/ is regenerated by `expo
 * prebuild`, so this has to be injected via a config plugin rather than
 * hand-edited — a raw Podfile patch would be silently wiped out.
 */
const withFmtConstevalFix = (config) =>
  withPodfile(config, (config) => {
    const marker = 'post_install do |installer|';
    if (!config.modResults.contents.includes(marker)) return config;
    if (config.modResults.contents.includes('fmt consteval workaround')) return config;

    const patch = `${marker}
    # fmt consteval workaround: Xcode 16.3+'s Clang rejects fmt's consteval
    # basic_format_string constructor as "not a constant expression". Strip
    # the keyword from the vendored headers so fmt falls back to its
    # non-consteval path, same as it already does for older broken Clangs.
    fmt_dir = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt')
    if Dir.exist?(fmt_dir)
      Dir.glob(File.join(fmt_dir, '**', '*.h')).each do |header|
        original = File.read(header)
        patched = original.gsub(/\\bconsteval\\b[ \\t]*/, '')
        File.write(header, patched) if patched != original
      end
    end`;

    config.modResults.contents = config.modResults.contents.replace(marker, patch);
    return config;
  });

module.exports = createRunOncePlugin(withFmtConstevalFix, 'withFmtConstevalFix', '2.0.0');
