import { Link } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

const sample = {
  handId: 'cash-aurora-1722864000-4821',
  tableId: 'cash-aurora',
  generatedAt: '2026-08-05T12:20:03.000Z',
  deckCommitment: '8e0f8ab1f7604828b3f8d06adfab565f4ec3f0f6a2f2f2f6efc85d29491f3f7c',
  actions: [
    'p1 bet $20 preflop',
    'p2 call $20 preflop',
    'p3 fold preflop',
  ],
  result: 'Winner: p1, Pot: $60, Hand: Pair',
};

export default function HandVerificationScreen() {
  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
      <Text style={styles.eyebrow}>FAIR PLAY CENTER</Text>
      <Text style={styles.title}>Hand Verification</Text>
      <Text style={styles.subtitle}>Transparent hand logs generated by the server-side dealer engine.</Text>

      <View style={styles.card}>
        <Text style={styles.label}>Hand ID</Text>
        <Text style={styles.value}>{sample.handId}</Text>

        <Text style={styles.label}>Table</Text>
        <Text style={styles.value}>{sample.tableId}</Text>

        <Text style={styles.label}>Generated</Text>
        <Text style={styles.value}>{sample.generatedAt}</Text>

        <Text style={styles.label}>Deck Commitment</Text>
        <Text style={styles.hash}>{sample.deckCommitment}</Text>
      </View>

      <View style={styles.card}>
        <Text style={styles.sectionTitle}>Action Timeline</Text>
        {sample.actions.map((line) => (
          <Text style={styles.timelineRow} key={line}>• {line}</Text>
        ))}
      </View>

      <View style={styles.card}>
        <Text style={styles.sectionTitle}>Outcome</Text>
        <Text style={styles.value}>{sample.result}</Text>
        <Text style={styles.note}>No claim of provably fair cryptographic proofs is made. This page exposes transparent, auditable server records.</Text>
      </View>

      <Link href="/table" asChild>
        <Pressable style={styles.button}>
          <Text style={styles.buttonText}>Back to table</Text>
        </Pressable>
      </Link>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#060816' },
  content: { padding: 20, paddingTop: 48, gap: 14 },
  eyebrow: { color: '#7ED3FF', letterSpacing: 1.8, fontSize: 11, fontWeight: '700' },
  title: { color: '#F4F7FF', fontSize: 30, fontWeight: '800' },
  subtitle: { color: '#A8B7D8', lineHeight: 20 },
  card: {
    backgroundColor: '#101B34',
    borderWidth: 1,
    borderColor: '#28426D',
    borderRadius: 16,
    padding: 14,
    gap: 6,
  },
  label: { color: '#88A7DC', fontSize: 12, fontWeight: '700' },
  value: { color: '#E9F1FF' },
  hash: { color: '#C3D5F7', fontSize: 12, lineHeight: 18 },
  sectionTitle: { color: '#F4F7FF', fontSize: 16, fontWeight: '700' },
  timelineRow: { color: '#D6E3FF' },
  note: { color: '#8AA2CA', fontSize: 12, lineHeight: 18, marginTop: 4 },
  button: {
    backgroundColor: '#3E8FFF',
    borderRadius: 12,
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 4,
  },
  buttonText: { color: '#FFF', fontWeight: '700' },
});
